version: 1
disable_existing_loggers: true
formatters:
  default:
    '()': logging.Formatter
    fmt:  '%(asctime)s - %(name)20s - %(levelname)7s - %(message)s'
handlers:
  default:
    '()': logging.StreamHandler
    level: INFO
    formatter: default
    stream: ext://sys.stdout
    filters: []
loggers:
  emuse:
    handlers: [default]
    level: DEBUG
    propagate: True
  fastapi:
    handlers: [default]
    level: INFO
    propagate: True
  httpcore:
    handlers: [default]
    level: ERROR
    propagate: True
  httpx:
    handlers: [default]
    level: ERROR
    propagate: True
  logfire:
    handlers: [default]
    level: ERROR
    propagate: True
  pydantic:
    handlers: [default]
    level: INFO
    propagate: True
  urllib3.connectionpool:
    handlers: [default]
    level: WARNING
    propagate: True
  uvicorn:
    handlers: [default]
    level: INFO
    propagate: False
  uvicorn.access:
    handlers: [default]
    level: INFO
    propagate: False
  uvicorn.error:
    handlers: [default]
    level: ERROR
    propagate: False
  uvicorn.asgi:
    handlers: [default]
    level: INFO
    propagate: False
